name: Build VPM Listing

on: 
    workflow_dispatch:
    push:
      branches: main
      paths: source.json

concurrency:
    group: "pages"
    cancel-in-progress: true

env:
    listPublishDirectory: front
    pathToCi: ci
      
jobs:
    # Build job
    build:
        name: build-listing
        environment:
          name: github-pages
          url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4 # check out this repo
          - uses: actions/checkout@v4 # check out automation repo
            with:
              repository: spokeek/package-list-action
              path: ${{env.pathToCi}}
              clean: false # otherwise the local repo will no longer be checked out
                            
          - name: Build Package Version Listing
            run: ${{env.pathToCi}}/build.cmd BuildMultiPackageListing --root ${{env.pathToCi}} --list-publish-directory $GITHUB_WORKSPACE/${{env.listPublishDirectory}}
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     
          - name: Setup Pages
            uses: actions/configure-pages@v3
            
          - name: Upload artifact
            uses: actions/upload-pages-artifact@v1
            with:
              path: ${{env.listPublishDirectory}}
              
          - name: Deploy to GitHub Pages
            id: deployment
            uses: actions/deploy-pages@v2
      
    # # Deploy job
    # deploy:
    #   # Add a dependency to the build job
    #   needs: build
  
    #   # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    #   permissions:
    #     pages: write      # to deploy to Pages
    #     id-token: write   # to verify the deployment originates from an appropriate source
  
    #   # Deploy to the github-pages environment
    #   environment:
    #     name: github-pages
    #     url: ${{ steps.deployment.outputs.page_url }}
    
    #   # Specify runner + deployment step
    #   runs-on: ubuntu-latest
    #   steps:
    #     - name: Deploy to GitHub Pages
    #       id: deployment
    #       uses: actions/deploy-pages@v2 # or the latest "vX.X.X" version tag for this action